let books = [
  {
    id: "b1",
    title: "Shadow of the Wind",
    author: "Carlos Ruiz",
    genre: ["Mystery", "Drama"],
  },
  {
    id: "b2",
    title: "Digital Fortress",
    author: "Dan Brown",
    genre: ["Thriller", "Tech"],
  },
  { id: "b3", title: "Silent Echo", author: "Mira Grant", genre: ["Sci-Fi"] },
  {
    id: "b4",
    title: "Broken Wings",
    author: "Khalil Gibran",
    genre: ["Classic", "Romance"],
  },
  {
    id: "b5",
    title: "The Last Empire",
    author: "Brandon Sanderson",
    genre: ["Fantasy"],
  },
  { id: "b6", title: "Ocean Deep", author: "Lara Finch", genre: ["Adventure"] },
  {
    id: "b7",
    title: "Mind Games",
    author: "T.J. Blake",
    genre: ["Psychology", "Thriller"],
  },
  {
    id: "b8",
    title: "Fire Within",
    author: "Nora Roberts",
    genre: ["Romance"],
  },
  { id: "b9", title: "Code Zero", author: "James Rollins", genre: ["Action"] },
  { id: "b10", title: "Winter Sun", author: "Elena Gray", genre: ["Drama"] },
  { id: "b11", title: "Hidden Truths", author: "Ava Reed", genre: ["Mystery"] },
  { id: "b12", title: "Skybound", author: "Rick Yancey", genre: ["Sci-Fi"] },
  { id: "b13", title: "Desert Storm", author: "Ahmed Khan", genre: ["War"] },
  { id: "b14", title: "Golden Path", author: "Li Wei", genre: ["Philosophy"] },
  { id: "b15", title: "Neon City", author: "J. Carter", genre: ["Cyberpunk"] },
  {
    id: "b16",
    title: "The Forgotten",
    author: "Sophie Lane",
    genre: ["Drama"],
  },
  { id: "b17", title: "Nightfall", author: "Isaac Asimov", genre: ["Sci-Fi"] },
  {
    id: "b18",
    title: "Lost Horizon",
    author: "James Hilton",
    genre: ["Adventure"],
  },
  {
    id: "b19",
    title: "Crimson Peak",
    author: "Victor Hale",
    genre: ["Horror"],
  },
  {
    id: "b20",
    title: "Dream Catcher",
    author: "Emily Stone",
    genre: ["Fantasy"],
  },
];

let games = [
  { id: "g1", title: "Cyber Clash", platform: ["PC", "PS5"] },
  { id: "g2", title: "Dragon Realms", platform: ["PC", "Xbox"] },
  { id: "g3", title: "Speed Racer X", platform: ["PS5"] },
  { id: "g4", title: "Zombie Night", platform: ["PC"] },
  { id: "g5", title: "Battle Arena", platform: ["Mobile", "PC"] },
  { id: "g6", title: "Galaxy Wars", platform: ["Xbox"] },
  { id: "g7", title: "Island Survival", platform: ["PC"] },
  { id: "g8", title: "Hero Legends", platform: ["Mobile"] },
  { id: "g9", title: "Mystic Quest", platform: ["Switch"] },
  { id: "g10", title: "Racing Storm", platform: ["PS4", "PS5"] },
  { id: "g11", title: "Shadow Strike", platform: ["PC"] },
  { id: "g12", title: "Warzone Elite", platform: ["Xbox", "PC"] },
  { id: "g13", title: "Puzzle World", platform: ["Mobile"] },
  { id: "g14", title: "Alien Attack", platform: ["PC"] },
  { id: "g15", title: "Dungeon Escape", platform: ["Switch"] },
  { id: "g16", title: "Sky Fighters", platform: ["PC", "Xbox"] },
  { id: "g17", title: "City Builder Pro", platform: ["PC"] },
  { id: "g18", title: "Fantasy Clash", platform: ["Mobile"] },
  { id: "g19", title: "Sniper Ops", platform: ["PS5"] },
  { id: "g20", title: "Robo Wars", platform: ["PC", "Mobile"] },
];

let reviews = [
  { id: "r1", rating: 5, content: "Amazing experience!" },
  { id: "r2", rating: 4, content: "Really good but could improve." },
  { id: "r3", rating: 3, content: "Average overall." },
  { id: "r4", rating: 5, content: "Loved every moment." },
  { id: "r5", rating: 2, content: "Not what I expected." },
  { id: "r6", rating: 1, content: "Very disappointing." },
  { id: "r7", rating: 4, content: "Solid and enjoyable." },
  { id: "r8", rating: 5, content: "Highly recommend!" },
  { id: "r9", rating: 3, content: "Decent but forgettable." },
  { id: "r10", rating: 4, content: "Worth checking out." },
  { id: "r11", rating: 5, content: "Exceptional quality." },
  { id: "r12", rating: 2, content: "Could be much better." },
  { id: "r13", rating: 3, content: "It was okay." },
  { id: "r14", rating: 4, content: "Enjoyed the story." },
  { id: "r15", rating: 5, content: "Absolutely fantastic!" },
  { id: "r16", rating: 1, content: "Waste of time." },
  { id: "r17", rating: 4, content: "Pretty good overall." },
  { id: "r18", rating: 5, content: "Masterpiece." },
  { id: "r19", rating: 3, content: "Nothing special." },
  { id: "r20", rating: 4, content: "Good value." },
];

let authors = [
  { id: "a1", name: "John Carter", verified: true },
  { id: "a2", name: "Emily Stone", verified: false },
  { id: "a3", name: "Michael Reed", verified: true },
  { id: "a4", name: "Sophia Lane", verified: false },
  { id: "a5", name: "David Kim", verified: true },
  { id: "a6", name: "Olivia Brown", verified: true },
  { id: "a7", name: "Liam Wilson", verified: false },
  { id: "a8", name: "Noah Taylor", verified: true },
  { id: "a9", name: "Ava Martinez", verified: false },
  { id: "a10", name: "Ethan Clark", verified: true },
  { id: "a11", name: "Mia Lewis", verified: false },
  { id: "a12", name: "Lucas Hall", verified: true },
  { id: "a13", name: "Amelia Young", verified: false },
  { id: "a14", name: "James Allen", verified: true },
  { id: "a15", name: "Isabella King", verified: true },
  { id: "a16", name: "Benjamin Scott", verified: false },
  { id: "a17", name: "Charlotte Green", verified: true },
  { id: "a18", name: "Henry Adams", verified: false },
  { id: "a19", name: "Ella Baker", verified: true },
  { id: "a20", name: "Daniel Nelson", verified: false },
];
